configs:
  # general optimization parameters:
  batch_size: 10000
  max_epochs: 5000
  learning_rate: .005
  min_delta: 0.0000000008
  patience: 100
  single_epoch_test_run: False
  which_data: 'sim'
  ndim: 1
  nitems: 10

